// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/connector/folder/read": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obter os emails para os parametros informados.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Email"
                ],
                "summary": "Leitura de Emails",
                "operationId": "GetEmailFilterFolder",
                "parameters": [
                    {
                        "description": "Requisição Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.GetEmailFilterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Dados recebidos!",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/response.EmailResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Requisição Inválida",
                        "schema": {
                            "$ref": "#/definitions/response.HttpResponse"
                        }
                    }
                }
            }
        },
        "/v1/connector/folder/read/full": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obter os emails para os parametros informados.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Email"
                ],
                "summary": "Leitura de Emails",
                "operationId": "GetEmailFilterFullFolder",
                "parameters": [
                    {
                        "description": "Requisição Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.GetEmailFilterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Dados recebidos!",
                        "schema": {
                            "$ref": "#/definitions/response.HttpResponse"
                        }
                    },
                    "400": {
                        "description": "Requisição Inválida",
                        "schema": {
                            "$ref": "#/definitions/response.HttpResponse"
                        }
                    }
                }
            }
        },
        "/v1/connector/folders": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obter os emails para os parametros informados.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Email"
                ],
                "summary": "Leitura de Emails",
                "operationId": "GetFolders",
                "parameters": [
                    {
                        "description": "Requisição Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.GetFoldersRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Dados recebidos!",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/response.MarkEmailResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Requisição Inválida",
                        "schema": {
                            "$ref": "#/definitions/response.HttpResponse"
                        }
                    }
                }
            }
        },
        "/v1/connector/mark": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obter os emails para os parametros informados.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Email"
                ],
                "summary": "Leitura de Emails",
                "operationId": "MarkEmailID",
                "parameters": [
                    {
                        "description": "Requisição Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.MarkEmailIDRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Dados recebidos!",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/response.MarkEmailResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Requisição Inválida",
                        "schema": {
                            "$ref": "#/definitions/response.HttpResponse"
                        }
                    }
                }
            }
        },
        "/v1/connector/move": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obter os emails para os parametros informados.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Email"
                ],
                "summary": "Leitura de Emails",
                "operationId": "MoveTo",
                "parameters": [
                    {
                        "description": "Requisição Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.MoveToRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Dados recebidos!",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/response.MarkEmailResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Requisição Inválida",
                        "schema": {
                            "$ref": "#/definitions/response.HttpResponse"
                        }
                    }
                }
            }
        },
        "/v1/connector/read": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obter os emails para os parametros informados.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Email"
                ],
                "summary": "Leitura de Emails",
                "operationId": "GetEmailFilter",
                "parameters": [
                    {
                        "description": "Requisição Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.GetEmailFilterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Dados recebidos!",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/response.EmailResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Requisição Inválida",
                        "schema": {
                            "$ref": "#/definitions/response.HttpResponse"
                        }
                    }
                }
            }
        },
        "/v1/connector/read/full": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obter os emails para os parametros informados.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Email"
                ],
                "summary": "Leitura de Emails",
                "operationId": "GetEmailFilterFull",
                "parameters": [
                    {
                        "description": "Requisição Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.GetEmailFilterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Dados recebidos!",
                        "schema": {
                            "$ref": "#/definitions/response.HttpResponse"
                        }
                    },
                    "400": {
                        "description": "Requisição Inválida",
                        "schema": {
                            "$ref": "#/definitions/response.HttpResponse"
                        }
                    }
                }
            }
        },
        "/v1/open/token": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obter os dados de token JWT para acesso.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get Token",
                "operationId": "GetToken",
                "parameters": [
                    {
                        "description": "Requisição Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.GetTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Dados recebidos!",
                        "schema": {
                            "$ref": "#/definitions/response.HttpResponse"
                        }
                    },
                    "400": {
                        "description": "Requisição Inválida",
                        "schema": {
                            "$ref": "#/definitions/response.HttpResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "request.GetEmailFilterRequest": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "Flag para retornar a contagem total",
                    "type": "boolean"
                },
                "expand": {
                    "description": "Propriedades adicionais para expandir",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "filter": {
                    "description": "Condição de filtro",
                    "type": "string"
                },
                "folder_id": {
                    "type": "string"
                },
                "include_hidden_messages": {
                    "description": "Flag para incluir mensagens ocultas",
                    "type": "boolean"
                },
                "orderby": {
                    "description": "Ordenação dos resultados",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "search": {
                    "description": "Termo de pesquisa",
                    "type": "string"
                },
                "select": {
                    "description": "Seleção de campos específicos",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "skip": {
                    "description": "Número de registros para ignorar",
                    "type": "integer"
                },
                "top": {
                    "description": "Número máximo de registros a retornar",
                    "type": "integer"
                }
            }
        },
        "request.GetFoldersRequest": {
            "type": "object",
            "properties": {
                "folder": {
                    "type": "string"
                }
            }
        },
        "request.GetTokenRequest": {
            "type": "object",
            "required": [
                "key"
            ],
            "properties": {
                "key": {
                    "type": "string"
                }
            }
        },
        "request.MarkEmailIDRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "request.MoveToRequest": {
            "type": "object",
            "properties": {
                "folder": {
                    "type": "string"
                },
                "id": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "response.AttachmentResponse": {
            "type": "object",
            "properties": {
                "base64": {
                    "type": "string"
                },
                "content_type": {
                    "description": "Tipo MIME do anexo (ex: image/png, application/pdf)",
                    "type": "string"
                },
                "id": {
                    "description": "ID do anexo (caso disponível)",
                    "type": "string"
                },
                "is_inline": {
                    "description": "Indica se o anexo é inline",
                    "type": "boolean"
                },
                "last_modified_date_time": {
                    "description": "Data e hora da última modificação do anexo",
                    "type": "string"
                },
                "name": {
                    "description": "Nome do anexo",
                    "type": "string"
                },
                "size": {
                    "description": "Tamanho do anexo em bytes",
                    "type": "integer"
                }
            }
        },
        "response.EmailResponse": {
            "type": "object",
            "properties": {
                "attachments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.AttachmentResponse"
                    }
                },
                "bcc_recipients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.RecipientResponse"
                    }
                },
                "body_content": {
                    "type": "string"
                },
                "body_content_type": {
                    "type": "string"
                },
                "cc_recipients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.RecipientResponse"
                    }
                },
                "conversation_id": {
                    "type": "string"
                },
                "from_email": {
                    "type": "string"
                },
                "from_name": {
                    "type": "string"
                },
                "has_attachments": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "importance": {
                    "type": "string"
                },
                "internet_message_id": {
                    "type": "string"
                },
                "is_read": {
                    "type": "boolean"
                },
                "received_date_time": {
                    "type": "string"
                },
                "sender_email": {
                    "type": "string"
                },
                "sender_name": {
                    "type": "string"
                },
                "sent_date_time": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                },
                "to_recipients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.RecipientResponse"
                    }
                }
            }
        },
        "response.HttpResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "response.MarkEmailResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "id": {
                    "type": "string"
                }
            }
        },
        "response.RecipientResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "outlook-connector",
	Description:      "Api integração connector de emails outlook",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
