basePath: /api
definitions:
  request.GetEmailFilterRequest:
    properties:
      count:
        description: Flag para retornar a contagem total
        type: boolean
      expand:
        description: Propriedades adicionais para expandir
        items:
          type: string
        type: array
      filter:
        description: Condição de filtro
        type: string
      folder_id:
        type: string
      include_hidden_messages:
        description: Flag para incluir mensagens ocultas
        type: boolean
      orderby:
        description: Ordenação dos resultados
        items:
          type: string
        type: array
      search:
        description: Termo de pesquisa
        type: string
      select:
        description: Seleção de campos específicos
        items:
          type: string
        type: array
      skip:
        description: Número de registros para ignorar
        type: integer
      top:
        description: Número máximo de registros a retornar
        type: integer
    type: object
  request.GetFoldersRequest:
    properties:
      folder:
        type: string
    type: object
  request.GetTokenRequest:
    properties:
      key:
        type: string
    required:
    - key
    type: object
  request.MarkEmailIDRequest:
    properties:
      id:
        items:
          type: string
        type: array
    type: object
  request.MoveToRequest:
    properties:
      folder:
        type: string
      id:
        items:
          type: string
        type: array
    type: object
  response.AttachmentResponse:
    properties:
      base64:
        type: string
      content_type:
        description: 'Tipo MIME do anexo (ex: image/png, application/pdf)'
        type: string
      id:
        description: ID do anexo (caso disponível)
        type: string
      is_inline:
        description: Indica se o anexo é inline
        type: boolean
      last_modified_date_time:
        description: Data e hora da última modificação do anexo
        type: string
      name:
        description: Nome do anexo
        type: string
      size:
        description: Tamanho do anexo em bytes
        type: integer
    type: object
  response.EmailResponse:
    properties:
      attachments:
        items:
          $ref: '#/definitions/response.AttachmentResponse'
        type: array
      bcc_recipients:
        items:
          $ref: '#/definitions/response.RecipientResponse'
        type: array
      body_content:
        type: string
      body_content_type:
        type: string
      cc_recipients:
        items:
          $ref: '#/definitions/response.RecipientResponse'
        type: array
      conversation_id:
        type: string
      from_email:
        type: string
      from_name:
        type: string
      has_attachments:
        type: boolean
      id:
        type: string
      importance:
        type: string
      internet_message_id:
        type: string
      is_read:
        type: boolean
      received_date_time:
        type: string
      sender_email:
        type: string
      sender_name:
        type: string
      sent_date_time:
        type: string
      subject:
        type: string
      to_recipients:
        items:
          $ref: '#/definitions/response.RecipientResponse'
        type: array
    type: object
  response.HttpResponse:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
  response.MarkEmailResponse:
    properties:
      error: {}
      id:
        type: string
    type: object
  response.RecipientResponse:
    properties:
      address:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
  description: Api integração connector de emails outlook
  title: outlook-connector
  version: "1.0"
paths:
  /v1/connector/folders:
    post:
      description: Obter os emails para os parametros informados.
      operationId: GetFolders
      parameters:
      - description: Requisição Body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.GetFoldersRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Dados recebidos!
          schema:
            allOf:
            - $ref: '#/definitions/response.HttpResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/response.MarkEmailResponse'
                  type: array
              type: object
        "400":
          description: Requisição Inválida
          schema:
            $ref: '#/definitions/response.HttpResponse'
      security:
      - ApiKeyAuth: []
      summary: Leitura de Emails
      tags:
      - Email
  /v1/connector/mark:
    post:
      description: Obter os emails para os parametros informados.
      operationId: MarkEmailID
      parameters:
      - description: Requisição Body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.MarkEmailIDRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Dados recebidos!
          schema:
            allOf:
            - $ref: '#/definitions/response.HttpResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/response.MarkEmailResponse'
                  type: array
              type: object
        "400":
          description: Requisição Inválida
          schema:
            $ref: '#/definitions/response.HttpResponse'
      security:
      - ApiKeyAuth: []
      summary: Leitura de Emails
      tags:
      - Email
  /v1/connector/move:
    post:
      description: Obter os emails para os parametros informados.
      operationId: MoveTo
      parameters:
      - description: Requisição Body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.MoveToRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Dados recebidos!
          schema:
            allOf:
            - $ref: '#/definitions/response.HttpResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/response.MarkEmailResponse'
                  type: array
              type: object
        "400":
          description: Requisição Inválida
          schema:
            $ref: '#/definitions/response.HttpResponse'
      security:
      - ApiKeyAuth: []
      summary: Leitura de Emails
      tags:
      - Email
  /v1/connector/read:
    post:
      description: Obter os emails para os parametros informados.
      operationId: GetEmailFilterFolder
      parameters:
      - description: Requisição Body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.GetEmailFilterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Dados recebidos!
          schema:
            allOf:
            - $ref: '#/definitions/response.HttpResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/response.EmailResponse'
                  type: array
              type: object
        "400":
          description: Requisição Inválida
          schema:
            $ref: '#/definitions/response.HttpResponse'
      security:
      - ApiKeyAuth: []
      summary: Leitura de Emails
      tags:
      - Email
  /v1/connector/read/full:
    post:
      description: Obter os emails para os parametros informados.
      operationId: GetEmailFilterFullFolder
      parameters:
      - description: Requisição Body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.GetEmailFilterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Dados recebidos!
          schema:
            $ref: '#/definitions/response.HttpResponse'
        "400":
          description: Requisição Inválida
          schema:
            $ref: '#/definitions/response.HttpResponse'
      security:
      - ApiKeyAuth: []
      summary: Leitura de Emails
      tags:
      - Email
  /v1/open/token:
    post:
      description: Obter os dados de token JWT para acesso.
      operationId: GetToken
      parameters:
      - description: Requisição Body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.GetTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Dados recebidos!
          schema:
            $ref: '#/definitions/response.HttpResponse'
        "400":
          description: Requisição Inválida
          schema:
            $ref: '#/definitions/response.HttpResponse'
      security:
      - ApiKeyAuth: []
      summary: Get Token
      tags:
      - Auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
